# Generated by Django 4.2.4 on 2023-08-28 19:50

import datetime
from django.db import migrations, models
import remisiones.models


class Migration(migrations.Migration):

    dependencies = [
        ('remisiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisiones',
            name='codigo',
            field=remisiones.models.UpperField(default='<function uuid1 at 0x000001EB3DF267A0>', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='remisiones',
            name='fecha_despacho',
            field=models.DateField(default=datetime.date(2023, 8, 28)),
        ),
    ]
