# Generated by Django 4.2.4 on 2023-08-28 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='fecha_recepcion',
            field=models.DateField(default=datetime.date(2023, 8, 28)),
        ),
    ]
